{
  "openapi": "3.0.2",
  "info": {
    "title": "Wordtracker Keyword API",
    "description": "*First release: 09.04.19, last API release: 06.05.19, last API docs release: 02.06.19*\n## Introduction\n\n### Raw Google, YouTube, Amazon, eBay keyword search data\nThe `Wordtracker Keyword API 2.0` provides keywords and associated search volumes for a range of sources, including Google, YouTube, Amazon and eBay from 106 countries. This data comes from a ~18 million global anonymized panel supplied by [DDMR](https://ddmr.com) which makes it a very reliable, clean source of keywords (2.06 billion unique keywords from 5.5 billion searches). To use the API you will first need to [sign up here](https://wordtracker.3scale.net). For pricing and more general information, please take a [look here](https://www.wordtracker.com/api). \n\nPlease note that this is v2 of the Wordtracker Keyword API and currently includes keywords and search volumes from:\n- Google\n- YouTube\n- Amazon\n- eBay\n \nWe have search volumes for over 106 countries including (but not limited to):\n- Global (GL) (all countries merged together)\n- United States (US), Canada (CA), United Kingdom (GB), \n- Australia (AU), New Zealand (NZ), Brazil (BR), Germany (DE), \n- Spain (ES), France (FR), India (IN), Italy (IT), Mexico (MX),\n- Netherlands (NL), Turkey (TR), South Africa (ZA)\n\nFor the full list please see this spreadsheet [Wordtracker keyword API 2.0 | Countries](https://docs.google.com/spreadsheets/d/1GCMXn_l4K5QYg8ijj9Asb9iPtvaep1TmAL2MKwhQIIw/edit#gid=0)\n\n## Get going in 10 minutes!\nFirst [register for an API account](https://wordtracker.3scale.net) (30 day free trial available). You can then find the production ready Wordtracker Keyword API 2.0 server at: https://api.lc.wordtracker.com\n\nPlease make sure you add the `app_id` and `app_key` as authorisation.\nHere's an example [REST url](https://api.lc.wordtracker.com/v2/search?engine=google&country=us&seeds=dog&limit=10&type=broad&app_id=your_app_id&app_key=your_key) to query the /search method. \n\nPlease note: If the above url does not work, please check the version e.g. /v2, /v2.1 etc. You can also see the latest urls at https://api.lc.wordtracker.com.\n### Please choose from these options\n* [Register for an API account (30 day free trial available)](https://wordtracker.3scale.net)\n* [API pricing](http://www.wordtracker.com/api)\n* [Try the data out in the Wordtracker keyword tool](http://www.wordtracker.com)\n\n\n\n## Available metrics\n### Monthly keyword search volumes\nPlease note that we use a 12 month rolling window for monthly search volumes. This means that as a new month begins, the last 12 months of data is re-processed up until the close of the previous month. E.g. if today is May 1st then a new 12 month rolling window is created from May 2018 - Apr 2019. That also means you will see search volumes and # panelists for each of those last 12 months as well as a total volume & average volume for all months. \n\n### Majestic SEO link counts\nWordtracker have partnered with [MajesticSEO](http://www.majestic.com) who have the planet's largest Link Index database. Our 'global Google' keyword list has been matched against Majestic's database to allow you to see how much competition there is online for a given keyword. Keywords with high search volumes and a low link footprint present good SEO opportunities. \nNote: These metrics cover both 'on page' (title tag) and 'off page' (incomingl links).\n\nIf the 'majestic' parameter is set to True, the following additional [MajesticSEO](http://www.majestic.com) link count metrics are available:\n\n1. **exact_urls_in_title:** Number of URLs that contain the exact keyword phrase within the title tag. E.g. for the keyword 'dog training' this would match 'dog training' and 'i love dog training' but not 'training my dog'.    \n2. **exact_domains_in_title:** Number of unique root domains (not URLs) that contain the exact keyword phrase within the title tag.\n3. **exact_urls_in_url**: Number of URLs that contain the exact keyword phrase within the URL. E.g. for the keyword 'dog training', this would match http://www.domain.com/dog-training-is-cool.html or http://www.dog-training.com.\n4. **exact_domains_in_url**: Number of unique root domains (not URLs) that contain the exact keyword phrase in the url belonging to that root domain.\n5. **exact_urls_in_anchor**: Number of URLs that contain the exact keyword phrase within the external anchor text of at least one backlink.\n6. **exact_domains_in_anchor**: Number of root domains (not URLs) that contain the exact keyword phrase within the external anchor text of at least one backlink.\n7. **exact_urls_in_anchor_and_in_title**: Number of URLs that contain the exact keyword phrase within both within the title tag & also in the external anchor text of at least one backlink.\n8. **exact_domains_in_anchor_and_in_title**: Number of root domains (not URLs) that contain the exact keyword phrase within both the external anchor text of at least one backlink and within the title tag.\n9. **broad_urls_in_title**: Number of URLs that contain all the words in any order within the title tag. E.g. for the keyword 'dog training' this would match 'training my dog'.\n10. **broad_domains_in_title**: Number of unique root domains (not URLs) that contain all the words in any order within the title tag.\n11. **broad_urls_in_anchor**: Number of URLs that contain all the words in any order in the external anchor text of at least one backlink.\n12. **broad_domains_in_anchor**: Number of root domains (not URLs) that contain all the words in any order within the external anchor text of at least one backlink.\n13. **broad_urls_in_anchor_and_in_title**: Number of URLs that contain all the words in any order, both within the title tag & also in the external anchor text of at least one backlink.\n14. **broad_domains_in_anchor_and_in_title**: Number of root domains (not URLs) that contain all the words in any order within the external anchor text of at least one backlink and the title tag.\n\n## Releases  \n- **2.0.0**: 09.04.19: First release.\n- **2.0.1**: 23.04.19: Add Majestic link metrics.\n- **2.0.2**: 30.04.19: Add /stats/keyword and /stats/link calls.\n- **2.0.3**: 06.05.19: Add 106 countries, change country parameter to country_code, use ISO-3166-2 standard.\n\n",
    "termsOfService": "https://www.wordtracker.com/terms",
    "contact": {
      "name": "Wordtracker API Team",
      "url": "http://www.wordtracker.com",
      "email": "developers@wordtracker.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "2.0.3",
    "x-date": "2019-03-07T00:00:00.000Z",
    "x-logo": {
      "url": "https://s3.amazonaws.com/wordtracker-front-end-assets/images/wordtracker-logo-transparent.png",
      "backgroundColor": "#5195E9"
    }
  },
  "servers": [
    {
      "url": "https://api.lc.wordtracker.com/v1",
      "description": "Production server"
    }
  ],
  "paths": {
    "/search": {
      "get": {
        "summary": "/search (raw keyword suggestions for engine/country_code)",
        "description": "Search the Wordtracker Keyword API for raw keyword suggestions and monthly volumes using one or more seed terms.\n",
        "operationId": "search",
        "responses": {
          "200": {
            "description": "Monthly search volume for one or more specific seed terms for an engine and a country_code e.g. Google US. Also includes panelists per month, total volume, average volume for last 12 months, total months seen and the query parameters.",
            "content": {
              "application/json": {
                "examples": {
                  "firefox": {
                    "value": {
                      "results": [
                        {
                          "keyword": "firefox",
                          "total_volume_for_last_12_months": 25258,
                          "avg_volume_for_last_12_months": 2105,
                          "volume_by_month": [
                            {
                              "volume": 2336,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "volume": 2486,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "volume": 2410,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "panelist_ids_by_month": [
                            {
                              "ids": 1440,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "ids": 1384,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "ids": 1263,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "total_months_seen": 12
                        },
                        {
                          "keyword": "mozilla firefox",
                          "total_volume_for_last_12_months": 4013,
                          "avg_volume_for_last_12_months": 334,
                          "volume_by_month": [
                            {
                              "volume": 476,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "volume": 424,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "volume": 373,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "panelist_ids_by_month": [
                            {
                              "ids": 296,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "ids": 233,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "ids": 198,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "total_months_seen": 12
                        }
                      ],
                      "params": {
                        "engine": "google",
                        "country_code": "us",
                        "seeds": [
                          "firefox"
                        ],
                        "limit": 10,
                        "type": "broad",
                        "sort": "total"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/seeds"
        },
        {
          "$ref": "#/components/parameters/engine"
        },
        {
          "$ref": "#/components/parameters/country_code"
        },
        {
          "$ref": "#/components/parameters/type"
        },
        {
          "$ref": "#/components/parameters/sort"
        },
        {
          "$ref": "#/components/parameters/limit"
        },
        {
          "$ref": "#/components/parameters/scale"
        },
        {
          "$ref": "#/components/parameters/majestic"
        }
      ]
    },
    "/top": {
      "get": {
        "summary": "/top (keywords for an engine/country_code)",
        "description": "Fetches the top keywords (max 2000) for an engine and a country_code e.g. Google US.",
        "operationId": "top",
        "responses": {
          "200": {
            "description": "Top keywords for an engine and a country_code e.g. Google US for each month. Also includes panelists per month, total volume, average volume for last 12 months, total months seen and the query parameters.",
            "content": {
              "application/json": {
                "examples": {
                  "firefox": {
                    "value": {
                      "results": [
                        {
                          "keyword": "youtube",
                          "total_volume_for_last_12_months": 1381715,
                          "avg_volume_for_last_12_months": 115143,
                          "volume_by_month": [
                            {
                              "volume": 133346,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "volume": 124478,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "volume": 121125,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "panelist_ids_by_month": [
                            {
                              "ids": 49189,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "ids": 42654,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "ids": 38276,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "total_months_seen": 12
                        },
                        {
                          "keyword": "gmail",
                          "total_volume_for_last_12_months": 933757,
                          "avg_volume_for_last_12_months": 77813,
                          "volume_by_month": [
                            {
                              "volume": 89668,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "volume": 85709,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "volume": 84670,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "panelist_ids_by_month": [
                            {
                              "ids": 29843,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "ids": 25751,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "ids": 23864,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "total_months_seen": 12
                        }
                      ],
                      "params": {
                        "engine": "google",
                        "country_code": "us",
                        "limit": 10,
                        "sort": "total"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/engine"
        },
        {
          "$ref": "#/components/parameters/country_code"
        },
        {
          "$ref": "#/components/parameters/sort"
        },
        {
          "$ref": "#/components/parameters/limit"
        },
        {
          "$ref": "#/components/parameters/scale"
        },
        {
          "$ref": "#/components/parameters/majestic"
        }
      ]
    },
    "/count": {
      "get": {
        "summary": "/count (total keywords available for engine/country_code)",
        "description": "Counts the total number of keywords matching specific parameters. The /search API is limited to a maximum of 2000 search results per query. The /count method tells you how many keywords there are in total.",
        "operationId": "count",
        "responses": {
          "200": {
            "description": "Total number of keywords matching the parameters e.g. specific engine and country_code.",
            "content": {
              "application/json": {
                "examples": {
                  "firefox": {
                    "value": {
                      "count": 1237,
                      "engine": "google",
                      "country_code": "us",
                      "seeds": "hello world",
                      "type": "broad"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/seeds"
        },
        {
          "$ref": "#/components/parameters/engine"
        },
        {
          "$ref": "#/components/parameters/country_code"
        },
        {
          "$ref": "#/components/parameters/type"
        }
      ]
    },
    "/periods": {
      "get": {
        "summary": "/periods (last 12 months as a list)",
        "description": "Get all the available time periods for the keyword data, usually the last 12 months.",
        "operationId": "periods",
        "responses": {
          "200": {
            "description": "All the available time periods for the keyword data, usually the last 12 months.",
            "content": {
              "application/json": {
                "examples": {
                  "result": {
                    "value": [
                      201803,
                      201804,
                      201805,
                      201806,
                      201807,
                      201808,
                      201809,
                      201810,
                      201811,
                      201812,
                      201901,
                      201902
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      }
    },
    "/stats/keyword": {
      "get": {
        "summary": "/stats/keyword (for each engine/country_code)",
        "description": "Returns statistics about the whole dataset for a specific engine and country_code e.g. max, count, sum, avg.",
        "operationId": "stats/keyword",
        "responses": {
          "200": {
            "description": "All the statistics about the whole dataset e.g. total number of keywords. Please note that these statistics will vary based on the engine & country_code specified in the parameters.",
            "content": {
              "application/json": {
                "examples": {
                  "result": {
                    "value": {
                      "max": 1403542,
                      "count": 82347238,
                      "sum": 230272251,
                      "avg": 2,
                      "engine": "google",
                      "country_code": "global",
                      "volume": "avg"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/engine"
        },
        {
          "$ref": "#/components/parameters/country_code"
        },
        {
          "$ref": "#/components/parameters/volume"
        },
        {
          "$ref": "#/components/parameters/scale"
        }
      ]
    },
    "/stats/link": {
      "get": {
        "summary": "/stats/link (Majestic link counts)",
        "description": "Returns statistics about the whole Majestic dataset.",
        "operationId": "stats/link",
        "responses": {
          "200": {
            "description": "Returns statistics about the Majestic link dataset e.g. IAAT (in anchor and title).",
            "content": {
              "application/json": {
                "examples": {
                  "result": {
                    "value": {
                      "iaat_max": 58915327,
                      "iaat_count": 82347238,
                      "iaat_sum": 26596478952,
                      "iaat_avg": 322
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      }
    },
    "/fetch": {
      "post": {
        "summary": "/fetch (exact search volume for multiple seed terms)",
        "description": "Whereas /search takes one or more seeds terms and returns up to 2000 keyword suggestions, /fetch is more specific. This method allows you to enter up to 500 seeds and retrieve the search volume (and panelist volumes) for each of those seeds specifically.",
        "operationId": "fetch",
        "responses": {
          "200": {
            "description": "Monthly search volume for one or more specific seed terms for an engine and a country_code\n e.g. Google US. Also includes panelists per month, total volume, average volume for\n last 12 months, total months seen and the query parameters.",
            "content": {
              "application/json": {
                "examples": {
                  "firefox": {
                    "value": {
                      "results": [
                        {
                          "keyword": "hello world",
                          "total_volume_for_last_12_months": 984,
                          "avg_volume_for_last_12_months": 82,
                          "volume_by_month": [
                            {
                              "volume": 93,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "volume": 89,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "volume": 113,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "panelist_ids_by_month": [
                            {
                              "ids": 59,
                              "year": "2018",
                              "month": "03"
                            },
                            {
                              "ids": 49,
                              "year": "2018",
                              "month": "04"
                            },
                            {
                              "ids": 58,
                              "year": "2018",
                              "month": "05"
                            },
                            "..."
                          ],
                          "total_months_seen": 12
                        }
                      ],
                      "params": {
                        "engine": "google",
                        "country_code": "us",
                        "seeds": "hello world",
                        "type": "exact",
                        "sort": "total"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/AccessForbidden"
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/seeds"
        },
        {
          "$ref": "#/components/parameters/engine"
        },
        {
          "$ref": "#/components/parameters/country_code"
        },
        {
          "$ref": "#/components/parameters/sort"
        },
        {
          "$ref": "#/components/parameters/scale"
        },
        {
          "$ref": "#/components/parameters/majestic"
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "properties": {
          "status": {
            "description": "The HTTP status code.",
            "maximum": 600,
            "minimum": 100,
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "type": {
            "description": "A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)] that identifies the problem type. It should provide human-readable documentation for the problem type. When this member is not present, its value is assumed to be \"about:blank\".",
            "type": "string"
          },
          "title": {
            "description": "A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.",
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "AccessForbidden": {
        "description": "Access forbidden, invalid API key was used",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "NotFound": {
        "description": "Resource was not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "parameters": {
      "seeds": {
        "name": "seeds",
        "in": "query",
        "description": "One or more strings (max 100). If entering a single seed then simply specify seeds=dog and if multiple then please use a list format e.g. seeds='dog','dog training'.\nThink of `seeds` as one or more of your starter ideas to get going with e.g. 'chocolate' or 'dog training'. This is a separate concept from keywords which are returned in the results and which show exactly what people are typing into the search boxes of the engines like Google. With some analysis some of these results will become your key words aka `keywords`.",
        "required": true,
        "schema": {
          "type": "array",
          "items": {}
        }
      },
      "engine": {
        "name": "engine",
        "in": "query",
        "description": "The engine that you want keyword suggestions and monthly volumes for. Default: `google`.",
        "required": true,
        "schema": {
          "enum": [
            "google",
            "youtube",
            "amazon",
            "ebay"
          ]
        }
      },
      "country_code": {
        "name": "country_code",
        "in": "query",
        "description": "Specifies the territory to search within. Two letter ISO 3166-2 country code or `GL` for global. \nGlobal means all ALL countries combined together. `US` is United States and `GB` is Great Britain (United Kingdom). Default: `GL`.",
        "required": true,
        "schema": {
          "enum": [
            "GL",
            "US",
            "CA",
            "GB",
            "AU",
            "NZ",
            "AE",
            "AM",
            "AR",
            "AT",
            "AZ",
            "BD",
            "BE",
            "BG",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CI",
            "CL",
            "CM",
            "CN",
            "CO",
            "CU",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FR",
            "GE",
            "GH",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IR",
            "IT",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KR",
            "KW",
            "KZ",
            "LB",
            "LK",
            "LT",
            "LV",
            "LY",
            "MA",
            "MD",
            "MG",
            "MM",
            "MN",
            "MX",
            "MY",
            "NG",
            "NL",
            "NO",
            "NP",
            "OM",
            "PE",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SK",
            "SN",
            "SV",
            "SY",
            "TH",
            "TN",
            "TR",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VE",
            "VN",
            "ZA",
            "ZW"
          ]
        }
      },
      "type": {
        "name": "type",
        "in": "query",
        "description": "### Broadest\n\nReturns keyword suggestions for any seed words. E.g. a search for 'dog training' returns suggestions for 'dog' or 'training' returns:\n* dog training\n* training dog\n* a dog is great\n* training day\n\n---\n### Broad\n\nReturns keyword suggestions for all words in any order. E.g. a search for 'dog training' returns:\n* dog training\n* training your dog\n\nbut not:\n\n* every dog has it's day\n\n\n---\n### Phrase\n\nReturns keyword suggestions for the exact phrase. E.g. a search for 'dog training' returns:\n* dog training\n* I love dog training\n* dog training is fun\n\n\n---\n### Wildcard\n\nAllows you to use the * and ? characters to specify a wildcard. E.g. tr* returns:\n* dog training\n* training your dog",
        "required": true,
        "schema": {
          "enum": [
            "broadest",
            "broad",
            "phrase",
            "wildcard"
          ]
        }
      },
      "sort": {
        "name": "sort",
        "in": "query",
        "description": "How you'd like to sort the results. Default `total`.\nTotal: Total searches for the last 12 months which means total search volume for Jan + Feb + Mar etc.\nAvg: Average searches for the last 12 months which means the total search volume for all 12 months / 12.",
        "required": true,
        "schema": {
          "enum": [
            "total",
            "avg"
          ]
        }
      },
      "limit": {
        "name": "limit",
        "in": "query",
        "description": "The maximum number of results which will be returned from the query.\nAn integer between 1 and 2000 (max).",
        "required": true,
        "schema": {
          "type": "integer"
        }
      },
      "scale": {
        "name": "scale",
        "in": "query",
        "description": "Scale the raw keyword sample volumes to match the engine's estimated search volumes.",
        "required": true,
        "schema": {
          "type": "boolean"
        }
      },
      "majestic": {
        "name": "majestic",
        "in": "query",
        "description": "Add Majestic (www.majestic.com) link count metrics.",
        "required": true,
        "schema": {
          "type": "boolean"
        }
      },
      "volume": {
        "name": "volume",
        "in": "query",
        "description": "Which volume to use for the last 12 months. I.e. the total for the last 12 months or the average.",
        "required": true,
        "schema": {
          "enum": [
            "total",
            "avg"
          ]
        }
      }
    },
    "securitySchemes": {
      "app_key": {
        "type": "apiKey",
        "description": "The Wordtracker Keyword API requires the app_id and app_key parameters in order to perform authorization. Authentication parameters must be present in the query string only, regardless of request method. To obtain these please sign up at https://wordtracker.3scale.net",
        "name": "app_key",
        "in": "header"
      },
      "app_id": {
        "type": "apiKey",
        "description": "The Wordtracker Keyword API requires the app_id and app_key parameters in order to perform authorization. Authentication parameters must be present in the query string only, regardless of request method. To obtain these please sign up at https://wordtracker.3scale.net",
        "name": "app_id",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "app_key": [],
      "app_id": []
    }
  ]
}
